[tool.poetry]
name = "repl_python3_20211068-13"
version = "0.1.0"
description = ""
authors = ["pyplusplusMF <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.2.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
